export default {
  // Version 2.6
  1501: {
    NAME: 'Aria',
    QUALITY: '5',
    ELEMENT: 'Ether',
    TYPE: 'Anomaly',
    SIGNATURE: '14150',
    FIXED_STATS: {
      BASE_HP: 7749,
      BASE_ATK: 863,
      BASE_DEF: 619,
      BASE_IMPACT: 87,
      BASE_AM: 115,
      BASE_AP: 116,
    },
  },
  1491: {
    NAME: 'Sunna',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Support',
    SIGNATURE: '14149',
    FIXED_STATS: {
      BASE_HP: 8477,
      BASE_ATK: 750,
      BASE_DEF: 600,
      BASE_IMPACT: 98,
      BASE_AM: 96,
      BASE_AP: 95,
    },
  },

  // Version 2.5
  1431: {
    NAME: 'Ye Shunguang',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Attack',
    SIGNATURE: '14143',
    FIXED_STATS: {
      BASE_HP: 7673,
      BASE_ATK: 938,
      BASE_DEF: 606,
      BASE_IMPACT: 83,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },
  1341: {
    NAME: 'Zhao',
    QUALITY: '5',
    ELEMENT: 'Ice',
    TYPE: 'Defense',
    SIGNATURE: '14134',
    FIXED_STATS: {
      BASE_HP: 9117,
      BASE_ATK: 765,
      BASE_DEF: 701,
      BASE_IMPACT: 93,
      BASE_AM: 93,
      BASE_AP: 96,
    },
  },

  // Version 2.4
  1481: {
    NAME: 'Dialyn',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Stun',
    SIGNATURE: '14148',
    FIXED_STATS: {
      BASE_HP: 8250,
      BASE_ATK: 758,
      BASE_DEF: 612,
      BASE_IMPACT: 110,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },
  1471: {
    NAME: 'Banyue',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Rupture',
    SIGNATURE: '14147',
    FIXED_STATS: {
      BASE_HP: 8497,
      BASE_ATK: 859,
      BASE_DEF: 445,
      BASE_IMPACT: 95,
      BASE_AM: 90,
      BASE_AP: 89,
    },
  },

  // Version 2.3
  1451: {
    NAME: 'Lucia',
    QUALITY: '5',
    ELEMENT: 'Ether',
    TYPE: 'Support',
    SIGNATURE: '14145',
    FIXED_STATS: {
      BASE_HP: 8477,
      BASE_ATK: 758,
      BASE_DEF: 594,
      BASE_IMPACT: 83,
      BASE_AM: 96,
      BASE_AP: 95,
      BASE_ER: 0.36,
    },
  },
  1441: {
    NAME: 'Manato',
    QUALITY: '4',
    ELEMENT: 'Fire',
    TYPE: 'Rupture',
    SIGNATURE: '13144',
    FIXED_STATS: {
      BASE_HP: 7724,
      BASE_ATK: 755,
      BASE_DEF: 443,
      BASE_IMPACT: 95,
      BASE_AM: 87,
      BASE_AP: 90,
    },
  },
  1051: {
    NAME: 'Yidhari',
    QUALITY: '5',
    ELEMENT: 'Ice',
    TYPE: 'Rupture',
    SIGNATURE: '14105',
    FIXED_STATS: {
      BASE_HP: 8497,
      BASE_ATK: 859,
      BASE_DEF: 448,
      BASE_IMPACT: 95,
      BASE_AM: 87,
      BASE_AP: 90,
    },
  },

  // Version 2.2
  1461: {
    NAME: 'Seed',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Attack',
    SIGNATURE: '14146',
    FIXED_STATS: {
      BASE_HP: 7673,
      BASE_ATK: 929,
      BASE_DEF: 612,
      BASE_IMPACT: 93,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },
  1301: {
    NAME: 'Orphie & Magus',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Attack',
    SIGNATURE: '14130',
    FIXED_STATS: {
      BASE_HP: 7788,
      BASE_ATK: 929,
      BASE_DEF: 612,
      BASE_IMPACT: 93,
      BASE_AM: 92,
      BASE_AP: 90,
      BASE_ER: 0.36,
    },
  },

  // Version 2.1
  1411: {
    NAME: 'Yuzuha',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Support',
    SIGNATURE: '14141',
    FIXED_STATS: {
      BASE_HP:  8829,
      BASE_ATK: 758,
      BASE_DEF: 612,
      BASE_IMPACT: 86,
      BASE_AM: 124,
      BASE_AP: 93,
    },
  },
  1401: {
    NAME: 'Alice',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Anomaly',
    SIGNATURE: '14140',
    FIXED_STATS: {
      BASE_HP:  7673,
      BASE_ATK: 880,
      BASE_DEF: 606,
      BASE_IMPACT: 86,
      BASE_AM: 142,
      BASE_AP: 118,
    },
  },

  // Version 2.0
  1421: {
    NAME: 'Pan Yinhu',
    QUALITY: '4',
    ELEMENT: 'Physical',
    TYPE: 'Defense',
    SIGNATURE: '13142',
    FIXED_STATS: {
      BASE_HP:  8453,
      BASE_ATK: 661,
      BASE_DEF: 712,
      BASE_IMPACT: 94,
      BASE_AM: 91,
      BASE_AP: 90,
      BASE_ER: 0.36,
    },
  },
  1391: {
    NAME: 'Ju Fufu',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Stun',
    SIGNATURE: '14139',
    FIXED_STATS: {
      BASE_HP:  8250,
      BASE_ATK: 765,
      BASE_DEF: 597,
      BASE_IMPACT: 118,
      BASE_AM: 93,
      BASE_AP: 96,
    },
  },
  1371: {
    NAME: 'Yixuan',
    QUALITY: '5',
    ELEMENT: 'Ether',
    TYPE: 'Rupture',
    SIGNATURE: '14137',
    FIXED_STATS: {
      BASE_HP:  8373,
      BASE_ATK: 872,
      BASE_DEF: 441,
      BASE_IMPACT: 93,
      BASE_AM: 92,
      BASE_AP: 90,
    },
  },

  // Version 1.7
  1331: {
    NAME: 'Vivian',
    QUALITY: '5',
    ELEMENT: 'Ether',
    TYPE: 'Anomaly',
    SIGNATURE: '14133',
    FIXED_STATS: {
      BASE_HP:  7673,
      BASE_ATK: 880,
      BASE_DEF: 606,
      BASE_IMPACT: 86,
      BASE_AM: 144,
      BASE_AP: 118,
    },
  },
  1291: {
    NAME: 'Hugo',
    QUALITY: '5',
    ELEMENT: 'Ice',
    TYPE: 'Attack',
    SIGNATURE: '14129',
    FIXED_STATS: {
      BASE_HP:  7940,
      BASE_ATK: 919,
      BASE_DEF: 616,
      BASE_IMPACT: 95,
      BASE_AM: 86,
      BASE_AP: 90,
    },
  },

  // Version 1.6
  1381: {
    NAME: 'Soldier 0 - Anby',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Attack',
    SIGNATURE: '14138',
    FIXED_STATS: {
      BASE_HP:  7673,
      BASE_ATK: 929,
      BASE_DEF: 612,
      BASE_IMPACT: 93,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },
  1361: {
    NAME: 'Trigger',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Stun',
    SIGNATURE: '14136',
    FIXED_STATS: {
      BASE_HP:  7923,
      BASE_ATK: 750,
      BASE_DEF: 600,
      BASE_IMPACT: 131,
      BASE_AM: 96,
      BASE_AP: 95,
    },
  },
  1351: {
    NAME: 'Pulchra',
    QUALITY: '4',
    ELEMENT: 'Physical',
    TYPE: 'Stun',
    SIGNATURE: '13135',
    FIXED_STATS: {
      BASE_HP:  7612,
      BASE_ATK: 665,
      BASE_DEF: 606,
      BASE_IMPACT: 136,
      BASE_AM: 92,
      BASE_AP: 90,
    },
  },

  // Version 1.5
  1321: {
    NAME: 'Evelyn',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Attack',
    SIGNATURE: '14132',
    FIXED_STATS: {
      BASE_HP:  7788,
      BASE_ATK: 929,
      BASE_DEF: 612,
      BASE_IMPACT: 93,
      BASE_AM: 92,
      BASE_AP: 90,
    },
  },
  1311: {
    NAME: 'Astra',
    QUALITY: '5',
    ELEMENT: 'Ether',
    TYPE: 'Support',
    SIGNATURE: '14131',
    FIXED_STATS: {
      BASE_HP:  8609,
      BASE_ATK: 715,
      BASE_DEF: 600,
      BASE_IMPACT: 83,
      BASE_AM: 93,
      BASE_AP: 92,
      BASE_ER: 0.36,
    },
  },

  // Version 1.4
  1201: {
    NAME: 'Harumasa',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Attack',
    SIGNATURE: '14120',
    FIXED_STATS: {
      BASE_HP:  7405,
      BASE_ATK: 915,
      BASE_DEF: 600,
      BASE_IMPACT: 90,
      BASE_AM: 80,
      BASE_AP: 95,
    },
  },
  1091: {
    NAME: 'Miyabi',
    QUALITY: '5',
    ELEMENT: 'Ice',
    TYPE: 'Anomaly',
    SIGNATURE: '14109',
    FIXED_STATS: {
      BASE_HP:  7673,
      BASE_ATK: 880,
      BASE_DEF: 606,
      BASE_IMPACT: 86,
      BASE_AM: 116,
      BASE_AP: 238,
    },
  },

  // Version 1.3
  1221: {
    NAME: 'Yanagi',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Anomaly',
    SIGNATURE: '14122',
    FIXED_STATS: {
      BASE_HP:  7789,
      BASE_ATK: 873,
      BASE_DEF: 613,
      BASE_IMPACT: 86,
      BASE_AM: 148,
      BASE_AP: 114,
    },
  },
  1161: {
    NAME: 'Lighter',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Stun',
    SIGNATURE: '14116',
    FIXED_STATS: {
      BASE_HP:  8253,
      BASE_ATK: 797,
      BASE_DEF: 612,
      BASE_IMPACT: 137,
      BASE_AM: 91,
      BASE_AP: 90,
    },
  },

  // Version 1.2
  1171: {
    NAME: 'Burnice',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Anomaly',
    SIGNATURE: '14117',
    FIXED_STATS: {
      BASE_HP:  7368,
      BASE_ATK: 863,
      BASE_DEF: 601,
      BASE_IMPACT: 83,
      BASE_AM: 118,
      BASE_AP: 120,
      BASE_ER: 0.36,
    },
  },
  1071: {
    NAME: 'Caesar',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Defense',
    SIGNATURE: '14107',
    FIXED_STATS: {
      BASE_HP:  9526,
      BASE_ATK: 712,
      BASE_DEF: 754,
      BASE_IMPACT: 123,
      BASE_AM: 87,
      BASE_AP: 90,
    },
  },

  // Version 1.1
  1271: {
    NAME: 'Seth',
    QUALITY: '4',
    ELEMENT: 'Electric',
    TYPE: 'Defense',
    SIGNATURE: '13127',
    FIXED_STATS: {
      BASE_HP:  8701,
      BASE_ATK: 643,
      BASE_DEF: 746,
      BASE_IMPACT: 94,
      BASE_AM: 86,
      BASE_AP: 90,
      BASE_ER: 0.36,
    },
  },
  1261: {
    NAME: 'Jane',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Anomaly',
    SIGNATURE: '14126',
    FIXED_STATS: {
      BASE_HP:  7789,
      BASE_ATK: 881,
      BASE_DEF: 607,
      BASE_IMPACT: 86,
      BASE_AM: 148,
      BASE_AP: 114,
    },
  },
  1251: {
    NAME: 'Qingyi',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Stun',
    SIGNATURE: '14125',
    FIXED_STATS: {
      BASE_HP:  8251,
      BASE_ATK: 758,
      BASE_DEF: 613,
      BASE_IMPACT: 136,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },

  // Version 1.0
  1281: {
    NAME: 'Piper',
    QUALITY: '4',
    ELEMENT: 'Physical',
    TYPE: 'Anomaly',
    SIGNATURE: '13128',
    FIXED_STATS: {
      BASE_HP:  6977,
      BASE_ATK: 758,
      BASE_DEF: 613,
      BASE_IMPACT: 86,
      BASE_AM: 116,
      BASE_AP: 118,
      BASE_ER: 0.36,
    },
  },
  1241: {
    NAME: 'Zhu Yuan',
    QUALITY: '5',
    ELEMENT: 'Ether',
    TYPE: 'Attack',
    SIGNATURE: '14124',
    FIXED_STATS: {
      BASE_HP:  7483,
      BASE_ATK: 919,
      BASE_DEF: 601,
      BASE_IMPACT: 90,
      BASE_AM: 93,
      BASE_AP: 92,
    },
  },
  1211: {
    NAME: 'Rina',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Support',
    SIGNATURE: '14121',
    FIXED_STATS: {
      BASE_HP:  8609,
      BASE_ATK: 717,
      BASE_DEF: 601,
      BASE_IMPACT: 83,
      BASE_AM: 93,
      BASE_AP: 92,
    },
  },
  1191: {
    NAME: 'Ellen',
    QUALITY: '5',
    ELEMENT: 'Ice',
    TYPE: 'Attack',
    SIGNATURE: '14119',
    FIXED_STATS: {
      BASE_HP:  7674,
      BASE_ATK: 938,
      BASE_DEF: 607,
      BASE_IMPACT: 93,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },
  1181: {
    NAME: 'Grace',
    QUALITY: '5',
    ELEMENT: 'Electric',
    TYPE: 'Anomaly',
    SIGNATURE: '14118',
    FIXED_STATS: {
      BASE_HP:  7483,
      BASE_ATK: 826,
      BASE_DEF: 601,
      BASE_IMPACT: 83,
      BASE_AM: 151,
      BASE_AP: 116,
    },
  },
  1151: {
    NAME: 'Lucy',
    QUALITY: '4',
    ELEMENT: 'Fire',
    TYPE: 'Support',
    SIGNATURE: '13115',
    FIXED_STATS: {
      BASE_HP:  8026,
      BASE_ATK: 659,
      BASE_DEF: 613,
      BASE_IMPACT: 86,
      BASE_AM: 94,
      BASE_AP: 93,
      BASE_ER: 0.36,
    },
  },
  1141: {
    NAME: 'Lycaon',
    QUALITY: '5',
    ELEMENT: 'Ice',
    TYPE: 'Stun',
    SIGNATURE: '14114',
    FIXED_STATS: {
      BASE_HP:  8416,
      BASE_ATK: 729,
      BASE_DEF: 607,
      BASE_IMPACT: 137,
      BASE_AM: 91,
      BASE_AP: 90,
    },
  },
  1131: {
    NAME: 'Soukaku',
    QUALITY: '4',
    ELEMENT: 'Ice',
    TYPE: 'Support',
    SIGNATURE: '13113',
    FIXED_STATS: {
      BASE_HP:  8026,
      BASE_ATK: 666,
      BASE_DEF: 598,
      BASE_IMPACT: 86,
      BASE_AM: 93,
      BASE_AP: 96,
      BASE_ER: 0.36,
    },
  },
  1121: {
    NAME: 'Ben',
    QUALITY: '4',
    ELEMENT: 'Fire',
    TYPE: 'Defense',
    SIGNATURE: '13112',
    FIXED_STATS: {
      BASE_HP:  8578,
      BASE_ATK: 653,
      BASE_DEF: 724,
      BASE_IMPACT: 95,
      BASE_AM: 86,
      BASE_AP: 90,
      BASE_ER: 0.36,
    },
  },
  1111: {
    NAME: 'Anton',
    QUALITY: '4',
    ELEMENT: 'Electric',
    TYPE: 'Attack',
    SIGNATURE: '13111',
    FIXED_STATS: {
      BASE_HP:  7219,
      BASE_ATK: 792,
      BASE_DEF: 623,
      BASE_IMPACT: 95,
      BASE_AM: 86,
      BASE_AP: 90,
    },
  },
  1101: {
    NAME: 'Koleda',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Stun',
    SIGNATURE: '14110',
    FIXED_STATS: {
      BASE_HP:  8127,
      BASE_ATK: 736,
      BASE_DEF: 595,
      BASE_IMPACT: 134,
      BASE_AM: 97,
      BASE_AP: 96,
    },
  },
  1081: {
    NAME: 'Billy',
    QUALITY: '4',
    ELEMENT: 'Physical',
    TYPE: 'Attack',
    SIGNATURE: '13108',
    FIXED_STATS: {
      BASE_HP:  6907,
      BASE_ATK: 787,
      BASE_DEF: 607,
      BASE_IMPACT: 91,
      BASE_AM: 92,
      BASE_AP: 91,
    },
  },
  1061: {
    NAME: 'Corin',
    QUALITY: '4',
    ELEMENT: 'Physical',
    TYPE: 'Attack',
    SIGNATURE: '13106',
    FIXED_STATS: {
      BASE_HP:  6977,
      BASE_ATK: 807,
      BASE_DEF: 605,
      BASE_IMPACT: 93,
      BASE_AM: 93,
      BASE_AP: 96,
    },
  },
  1041: {
    NAME: 'Soldier 11',
    QUALITY: '5',
    ELEMENT: 'Fire',
    TYPE: 'Attack',
    SIGNATURE: '14104',
    FIXED_STATS: {
      BASE_HP:  7674,
      BASE_ATK: 889,
      BASE_DEF: 613,
      BASE_IMPACT: 93,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },
  1031: {
    NAME: 'Nicole',
    QUALITY: '4',
    ELEMENT: 'Ether',
    TYPE: 'Support',
    SIGNATURE: '13103',
    FIXED_STATS: {
      BASE_HP:  8146,
      BASE_ATK: 649,
      BASE_DEF: 623,
      BASE_IMPACT: 88,
      BASE_AM: 90,
      BASE_AP: 93,
      BASE_ER: 0.36,
    },
  },
  1021: {
    NAME: 'Nekomata',
    QUALITY: '5',
    ELEMENT: 'Physical',
    TYPE: 'Attack',
    SIGNATURE: '14102',
    FIXED_STATS: {
      BASE_HP:  7560,
      BASE_ATK: 911,
      BASE_DEF: 588,
      BASE_IMPACT: 92,
      BASE_AM: 97,
      BASE_AP: 96,
    },
  },
  1011: {
    NAME: 'Anby',
    QUALITY: '4',
    ELEMENT: 'Electric',
    TYPE: 'Stun',
    SIGNATURE: '13101',
    FIXED_STATS: {
      BASE_HP:  7501,
      BASE_ATK: 659,
      BASE_DEF: 613,
      BASE_IMPACT: 136,
      BASE_AM: 94,
      BASE_AP: 93,
    },
  },
};
