import { GI, HSR, ZZZ } from '@/data';

export default {
  [GI]: {
    'FIGHT_PROP_HP': 'hp',
    'FIGHT_PROP_ATTACK': 'atk',
    'FIGHT_PROP_DEFENSE': 'def',
    'FIGHT_PROP_HP_PERCENT': 'hp%',
    'FIGHT_PROP_ATTACK_PERCENT': 'atk%',
    'FIGHT_PROP_DEFENSE_PERCENT': 'def%',
    'FIGHT_PROP_ELEMENT_MASTERY': 'elementalMastery',
    'FIGHT_PROP_CHARGE_EFFICIENCY': 'energyRecharge%',
    'FIGHT_PROP_WIND_ADD_HURT': 'anemoDmgBonus%',
    'FIGHT_PROP_ICE_ADD_HURT': 'cryoDmgBonus%',
    'FIGHT_PROP_GRASS_ADD_HURT': 'dendroDmgBonus%',
    'FIGHT_PROP_ELEC_ADD_HURT': 'electroDmgBonus%',
    'FIGHT_PROP_ROCK_ADD_HURT': 'geoDmgBonus%',
    'FIGHT_PROP_WATER_ADD_HURT': 'hydroDmgBonus%',
    'FIGHT_PROP_FIRE_ADD_HURT': 'pyroDmgBonus%',
    'FIGHT_PROP_PHYSICAL_ADD_HURT': 'physicalDmgBonus%',
    'FIGHT_PROP_CRITICAL': 'critRate%',
    'FIGHT_PROP_CRITICAL_HURT': 'critDmg%',
    'FIGHT_PROP_HEAL_ADD': 'healingBonus%'
  },
  [HSR]: {
    'HPDelta': 'hp',
    'AttackDelta': 'atk',
    'DefenceDelta': 'def',
    'HPAddedRatio': 'hp%',
    'AttackAddedRatio': 'atk%',
    'DefenceAddedRatio': 'def%',
    'CriticalChanceBase': 'critRate%',
    'CriticalChance': 'critRate%',
    'CriticalDamageBase': 'critDmg%',
    'CriticalDamage': 'critDmg%',
    'StatusProbabilityBase': 'effectHitRate%',
    'StatusProbability': 'effectHitRate%',
    'HealRatioBase': 'outgoingHealingBoost%',
    'SpeedDelta': 'spd',
    'FireAddedRatio': 'fireDmgBonus%',
    'IceAddedRatio': 'iceDmgBonus%',
    'ImaginaryAddedRatio': 'imaginaryDmgBonus%',
    'ThunderAddedRatio': 'lightningDmgBonus%',
    'PhysicalAddedRatio': 'physicalDmgBonus%',
    'QuantumAddedRatio': 'quantumDmgBonus%',
    'WindAddedRatio': 'windDmgBonus%',
    'BreakDamageAddedRatioBase': 'breakEffect%',
    'BreakDamageAddedRatio': 'breakEffect%',
    'SPRatioBase': 'energyRegenerationRate%',
    'StatusResistance': 'effectRes%',
    'ElationDamageAddedRatioBase': 'elation%',
    'ElationDamageAddedRatio': 'elation%'
  },
  [ZZZ]: {
    '11102': 'hp%',
    '11103': 'hp',
    '12102': 'atk%',
    '12103': 'atk',
    '12202': 'impact%',
    '13102': 'def%',
    '13103': 'def',
    '20103': 'critRate%',
    '21103': 'critDmg%',
    '23103': 'penRatio%',
    '23203': 'pen',
    '30502': 'energyRegen%',
    '31203': 'anomalyProficiency',
    '31402': 'anomalyMastery%',
    '31503': 'physicalDmgBonus%',
    '31603': 'fireDmgBonus%',
    '31703': 'iceDmgBonus%',
    '31803': 'electricDmgBonus%',
    '31903': 'etherDmgBonus%',
    '32303': 'windDmgBonus%',
  }
};
