export default {
  gi: {
    numMain: 5,
    numSub: 4,
    totalRolls: 40,
    rollsPerPiece: 8,
    firstIncrement: 5,
    matchStatsMain: ["ER"],
    matchStatsSub: ["ER"],
  },
  hsr: {
    numMain: 6,
    numSub: 4,
    totalRolls: 48,
    rollsPerPiece: 8,
    firstIncrement: 5,
    matchStatsMain: ["EHR", "SPD", "ERR"],
    matchStatsSub: ["EHR", "SPD"],
  },
  ww: {
    numMain: 5,
    numSub: 5,
    totalRolls: 25,
    rollsPerPiece: 5,
    firstIncrement: 1,
    matchStatsMain: ["ER"],
    matchStatsSub: ["ER"],
  },
  zzz: {
    numMain: 6,
    numSub: 4,
    totalRolls: 48,
    rollsPerPiece: 8,
    firstIncrement: 5,
    matchStatsMain: ["ER"],
    matchStatsSub: [],
  },
};
